name: Deploy pkgdown site to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up R environment
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # Cache R packages to speed up workflow
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-R-${{ hashFiles("**/DESCRIPTION") }}
          restore-keys: |
            ${{ runner.os }}-R-

      # Install dependencies
      - name: Install dependencies
        run: |
          install.packages("pkgdown")
          # Install other dependencies if needed
          if [ -f "DESCRIPTION" ]; then
            Rscript -e 'install.packages("devtools")'
            Rscript -e 'devtools::install_deps(dep = TRUE)'
          fi

      # Build pkgdown site
      - name: Build pkgdown site
        run: |
          Rscript -e 'pkgdown::build_site(clean = FALSE)'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # pkgdown by default outputs to docs/
          publish_branch: gh-pages